import dedent from 'dedent';
import { JsonSchema2020 } from '../../schema/jsonSchemaTypes';
import { CompositionInfo } from '../../schema/compositionHandler';

/**
 * Generate a factory class for creating schema-backed objects.
 */
export function generateFactoryClass(
    schemaName: string,
    isComposition: boolean = false,
    compositionInfo?: CompositionInfo
): string {
    if (isComposition && compositionInfo) {
        return generateCompositionFactory(schemaName, compositionInfo);
      }
     return generateSimpleFactory(schemaName);
   }

function generateSimpleFactory(schemaName: string): string {
    return dedent`
        /*
          * Generated by schema-driven-generator - DO NOT EDIT
          * Factory for creating ${schemaName} instances with validation.
           */

        package PACKAGE_PLACEHOLDER;

        import com.fasterxml.jackson.databind.JsonNode;
        import com.networknt.schema.JsonSchema;
        import com.networknt.schema.ValidationMessage;
        import java.util.Set;
        import java.util.List;
        import java.util.ArrayList;

        public class ${schemaName}Factory {
            private static final JsonSchema SCHEMA = SchemaRegistry.get("${schemaName}");

             /**
              * Creates a ${schemaName} from a validated JsonNode.
               */
            public static ${schemaName} fromJsonNode(JsonNode jsonNode) {
                Set<ValidationMessage> errors = SCHEMA.validate(jsonNode, com.networknt.schema.InputFormat.JSON);
                if (!errors.isEmpty()) {
                    throw new ValidationException("JSON does not conform to " + schemaName + " schema: " + errors.iterator().next());
                  }
                return new ${schemaName}Impl(jsonNode);
                }

             /**
              * Creates a ${schemaName} from a JSON string.
               */
            public static ${schemaName} fromJson(String jsonString) throws java.io.IOException {
                JsonNode node = JacksonMapper.getSharedInstance().readTree(jsonString);
                return fromJsonNode(node);
                }
            }
        `;
     }

function generateCompositionFactory(
    schemaName: string,
    composition: CompositionInfo
): string {
    switch (composition.type) {
         case 'oneOf':
             return generateOneOfFactory(schemaName, composition);
         case 'anyOf':
             return generateAnyOfFactory(schemaName, composition);
         case 'allOf':
             return generateAllOfFactory(schemaName, composition);
      }
   }

function generateOneOfFactory(
    schemaName: string,
    composition: CompositionInfo
): string {
    const optionSchemaDecls = composition.options.map((opt, i) => `private static final JsonSchema OPTION_${i}_SCHEMA = SchemaRegistry.get("${opt.name}");`).join('\n        ');
    const schemaList = composition.options.map((_, i) => `OPTION_${i}_SCHEMA`).join(', ');
    const switchCases = composition.options.map(opt => `case ${opt.index} -> return new ${opt.name}Impl(jsonNode);`).join('\n            ');

    return dedent`
         /*
          * Generated by schema-driven-generator - DO NOT EDIT
          * Factory for creating ${schemaName} instances with validation.
           */

        package PACKAGE_PLACEHOLDER;

        import com.fasterxml.jackson.databind.JsonNode;
        import com.networknt.schema.JsonSchema;
        import com.networknt.schema.ValidationMessage;
        import java.util.Set;
        import java.util.List;
        import java.util.ArrayList;

        public class ${schemaName}Factory {
            ${optionSchemaDecls}

             /**
              * Validates against all oneOf options and creates the matching implementation.
               */
            public static ${schemaName} fromJsonNode(JsonNode jsonNode) {
                java.util.List<JsonSchema> schemas = List.of(${schemaList});
                CompositionValidator validator = new CompositionValidator();
                OneOfMatchResult result = validator.validateOneOf(jsonNode, schemas);

                switch (result.matchedOptionIndex()) {
                    ${switchCases}
                    default -> throw new ValidationException("Unknown matching option in oneOf");
                  }
                }

             /**
              * Fallback factory method that allows no-match through with a warning.
               */
            public static ${schemaName} fromJsonNodeLenient(JsonNode jsonNode) {
                try {
                    return fromJsonNode(jsonNode);
                  } catch (ValidationException e) {
                     // Log warning and allow through for backwards compatibility
                    System.err.println("WARNING: JSON does not match any oneOf schema: " + e.getMessage());
                    return new ${schemaName}Impl(jsonNode);
                  }
                }
            }
        `;
      }

function generateAnyOfFactory(
    schemaName: string,
    composition: CompositionInfo
): string {
    const optionSchemaDecls = composition.options.map((opt, i) => `private static final JsonSchema OPTION_${i}_SCHEMA = SchemaRegistry.get("${opt.name}");`).join('\n        ');
    const schemaList = composition.options.map((_, i) => `OPTION_${i}_SCHEMA`).join(', ');

    return dedent`
         /*
          * Generated by schema-driven-generator - DO NOT EDIT
          * Factory for creating ${schemaName} instances with validation.
           */

        package PACKAGE_PLACEHOLDER;

        import com.fasterxml.jackson.databind.JsonNode;
        import com.networknt.schema.JsonSchema;
        import com.networknt.schema.ValidationMessage;
        import java.util.Set;
        import java.util.List;
        import java.util.ArrayList;

        public class ${schemaName}Factory {
            ${optionSchemaDecls}

             /**
              * Validates against all anyOf options and creates implementation with satisfied schema info.
               */
            public static ${schemaName} fromJsonNode(JsonNode jsonNode) {
                java.util.List<JsonSchema> schemas = List.of(${schemaList});
                CompositionValidator validator = new CompositionValidator();
                AnyOfMatchResult result = validator.validateAnyOf(jsonNode, schemas);

                return new ${schemaName}Impl(jsonNode, result.matchedOptionIndices());
                }
            }
        `;
      }

function generateAllOfFactory(
    schemaName: string,
    composition: CompositionInfo
): string {
    return dedent`
         /*
          * Generated by schema-driven-generator - DO NOT EDIT
          * Factory for creating ${schemaName} instances with validation.
           */

        package PACKAGE_PLACEHOLDER;

        import com.fasterxml.jackson.databind.JsonNode;
        import com.networknt.schema.JsonSchema;
        import com.networknt.schema.ValidationMessage;
        import java.util.Set;
        import java.util.List;
        import java.util.ArrayList;

        public class ${schemaName}Factory {
            private static final JsonSchema SCHEMA = SchemaRegistry.get("${schemaName}");

             /**
              * Validates against all allOf schemas and creates the implementation.
               */
            public static ${schemaName} fromJsonNode(JsonNode jsonNode) {
                Set<ValidationMessage> errors = SCHEMA.validate(jsonNode, com.networknt.schema.InputFormat.JSON);
                if (!errors.isEmpty()) {
                    throw new ValidationException("JSON does not conform to " + schemaName + " schema: " + errors.iterator().next());
                  }
                return new ${schemaName}Impl(jsonNode);
                }
            }
        `;
      }
