import dedent from 'dedent';
import { JsonSchema2020 } from '../../schema/jsonSchemaTypes';
import { mapJsonSchemaToJavaType, TypeMapping } from './typeMapper';

/**
 * Represents a property getter for a Java interface.
 */
export interface PropertyGetter {
    propertyName: string;
    javaName: string;
    typeMapping: TypeMapping;
    isRequired: boolean;
    description?: string;
}

/**
 * Generate property getters from a JSON Schema object.
 */
export function generatePropertyGetters(
    schema: JsonSchema2020,
    schemaName: string
): PropertyGetter[] {
    const getters: PropertyGetter[] = [];
    const requiredSet = new Set(schema.required || []);

    if (!schema.properties) {
        return getters;
      }

    for (const [propertyName, propSchema] of Object.entries(schema.properties)) {
        const jsPropSchema = propSchema as JsonSchema2020;
        const javaName = toCamelCase(propertyName);
        const isRequired = requiredSet.has(propertyName);

        const typeMapping = mapJsonSchemaToJavaType(jsPropSchema, {
            propertyName,
            schemaName: `${schemaName}${capitalize(propertyName)}`,
            isRequired
          });

        getters.push({
            propertyName,
            javaName,
            typeMapping,
            isRequired,
            description: jsPropSchema.description
          });
      }

    return getters;
}

/**
 * Generate the Java interface declaration.
 */
export function generateInterfaceJava(
    schemaName: string,
    getters: PropertyGetter[],
    extendsInterface?: string,
    isSealed: boolean = false,
    permittedSubtypes?: string[]
): string {
    const imports = collectImports(getters);
    const importBlock = imports.size > 0 
           ? Array.from(imports).sort().map(imp => 'import ' + imp).join('\n') + '\n' : '';
    return dedent`
        /*
         * Generated by schema-driven-generator - DO NOT EDIT
         * Interface for schema: ${schemaName}
         */

        package PACKAGE_PLACEHOLDER;

        ${importBlock}public interface ${schemaName}${extendsInterface ? ` extends ${extendsInterface}` : ''}${isSealed && permittedSubtypes ? ` permits ${permittedSubtypes.join(', ')}` : ''} {
            ${getters.map(getter => {
                if (getter.description) {
                    return dedent`

                  /**
                   * Gets the '${getter.propertyName}' property.
                    ${getter.isRequired ? ' * Required.' : ''}
                   */`;
                  }
                 return '';
              }).join('\n')}

            ${getters.map(getter => `${getter.typeMapping.javaType} get${capitalize(getter.javaName)}();`).join('\n          ')}

          /**
           * Access to the underlying JSON node for advanced use cases.
           */
          com.fasterxml.jackson.databind.JsonNode getRawNode();

          /**
           * Check if a property is present in the underlying JSON.
           */
          boolean hasProperty(String propertyName);
        }
      `;
}

/**
 * Generate a Java enum for JSON Schema enums.
 */
export function generateEnumJava(
    enumName: string,
    values: (string | number)[],
    valueType: 'string' | 'number' = 'string'
): string {
    const javaValueType = valueType === 'string' ? 'String' : 'Double';

    return dedent`
        /*
         * Generated by schema-driven-generator - DO NOT EDIT
         * Enum for: ${enumName}
         */

        package PACKAGE_PLACEHOLDER;

        public enum ${enumName} {
            ${(values as string[]).map(v => `${toEnumConstantName(v)}("${v}")`).join(',\n            ')};

            private final ${javaValueType} value;

            ${enumName}(${javaValueType} value) {
                this.value = value;
              }

            public static ${enumName} fromValue(${javaValueType} value) {
                for (${enumName} constant : values()) {
                    if (constant.value.equals(value)) return constant;
                  }
                throw new IllegalArgumentException("Unknown value: " + value);
              }

            public ${javaValueType} getValue() {
                return value;
              }
          }
      `;
}

function toEnumConstantName(value: string | number): string {
    const str = String(value).toUpperCase();
    return str.replace(/[^A-Z0-9_]/g, '_').replace(/^_+|_+$/g, '');
}

function collectImports(getters: PropertyGetter[]): Set<string> {
    const imports = new Set<string>();

    for (const getter of getters) {
        for (const imp of getter.typeMapping.imports) {
            if (!imp.startsWith('java.lang.')) {
                imports.add(imp + ';');
              }
          }
      }

    imports.add('com.fasterxml.jackson.databind.JsonNode;');
    return imports;
}

function toCamelCase(name: string): string {
     // Return as-is since JSON Schema properties should already be camelCase
    return name;
}

function capitalize(s: string): string {
    if (!s) return s;
    return s.charAt(0).toUpperCase() + s.slice(1);
}
